# this is supposed to run from a plain opensuse container

# global before_script to always install required packages
before_script:
   - zypper --non-interactive in make
   - zypper --non-interactive in gcc7
   - zypper --non-interactive in gcc7-fortran

# a job with two stages: compile and test
test_build:
   stage: build
   tags:
      - linux
   script:
      - SUFFIX=-7 make gcc=y lib64/frand123.so lib64/frand123.a
  
run_test: 
   before_script:
      - zypper --non-interactive in make
      - zypper --non-interactive in gcc7
      - zypper --non-interactive in gcc7-fortran
      - zypper --non-interactive in octave-cli
      - zypper --non-interactive in octave-forge-nan
      - zypper --non-interactive in octave-forge-statistics
   stage: test
   tags:
      - linux
   variables:
      CV: '0'
      CV_S: 'coverage:'
      N_TESTS: '2.' # FLOAT NUMBER!
   script:
      - SUFFIX=-7 make gcc=y testRandSingle && CV="$((CV + 1))"
      - CV_R=`echo "$CV $N_TESTS" | awk '{print $1/$2}'`
      - echo $CV_S "$CV_R"
      - SUFFIX=-7 make gcc=y testRandDouble && CV="$((CV + 1))"
      - CV_R=`echo "$CV $N_TESTS" | awk '{print $1/$2}'`
      - echo $CV_S "$CV_R"
   coverage: '/coverage: \d+\.\d+/'
   allow_failure: true
#  artifacts:
#    when: on_success
#    name: ...
#    paths:
#       - "*. ..."
