# this is supposed to run from a plain opensuse container

# global before_script to always install required packages
before_script:
   - zypper --non-interactive in make
   - zypper --non-interactive in gcc7
   - zypper --non-interactive in gcc7-fortran

# a job with two stages: compile and test
test_build:
   stage: build
   tags:
      - linux
   script:
      - SUFFIX=-7 make gcc=y lib64/frand123.so lib64/frand123.a
  
run_test: 
   before_script:
      - zypper --non-interactive in make
      - zypper --non-interactive in gcc7
      - zypper --non-interactive in gcc7-fortran
      - zypper --non-interactive in octave-cli
      - zypper --non-interactive in octave-forge-statistics
   stage: test
   tags:
      - linux
#  variables:
   script:
      - SUFFIX=-7 make gcc=y tests
#  coverage: '/regex/'
#  artifacts:
#    when: on_success
#    name: ...
#    paths:
#       - "*. ..."
